### ISSUE TITLE
Settings Toggle

### ISSUE THREAD

**Issue by RogueMaster** [culturally/flipper-zero-airtag#1]
Are you be able to make your changes toggle in settings to switch from Bluetooth (Yes, No, Airtag)?

**Comment by culturally** [comment]
Well theoretically yes if someone modifies it then it work like that but i personally think it does not matter as flipper functions same as if you would not change it the only difference is it shows as an AirTag

**Comment by RogueMaster** [comment]
Without it, it is not findable as an airtag, right? So it's not really the same as you may not want it to be found as easily, no?

**Comment by culturally** [comment]
well I guess you have a point. I will look at it and try to add another switch for airtag

**Comment by RogueMaster** [comment]
Have you tested to add this as an airtag to your phone?

**Comment by RogueMaster** [comment]
Aside from the settings update, this would also need a file to have a user configurable tag value so everyone doesn't broadcast the same tag...

**Comment by wallopthecat** [comment]
If I understand it right, the user configurable part will need to explain how to retrieve these tag values, and explain that they are only able to be added by using a non-paired airtag
